name: Terraform CI/CD

on:
  push:
    branches:
      - feature
      - main

  pull_request:
    branches:
      - main

jobs:

  # ==================================================
  # TERRAFORM CI/CD
  # ==================================================
  terraform:

    name: Terraform CI/CD

    runs-on: ubuntu-latest

    # ==================================================
    # TERRAFORM DIRECTORY
    # ==================================================
    defaults:
      run:
        working-directory: ./environment/dev

    # ==================================================
    # AZURE CREDENTIALS
    # ==================================================
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:

      # ==================================================
      # 1. CHECKOUT CODE
      # ==================================================
      - name: Checkout Code
        uses: actions/checkout@v4


      # ==================================================
      # 2. SETUP TERRAFORM
      # ==================================================
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      # ==================================================
      # 3. TERRAFORM VERSION
      # ==================================================
      - name: Terraform Version
        run: terraform version


      # ==================================================
      # 4. TERRAFORM INIT
      # ==================================================
      - name: Terraform Init
        run: terraform init


      # ==================================================
      # 5. TERRAFORM FORMAT CHECK
      # ==================================================
      - name: Terraform Format Check
        run: terraform fmt -check -recursive


      # ==================================================
      # 6. TERRAFORM VALIDATE
      # ==================================================
      - name: Terraform Validate
        run: terraform validate


      # ==================================================
      # 7. TERRAFORM PLAN
      # ==================================================
      - name: Terraform Plan
        run: terraform plan


      # ==================================================
      # 8. TERRAFORM APPLY
      # ==================================================
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve